language: d

d:
  - dmd-2.067.0

sudo: false

addons:
  apt:
    sources:
      - debian-sid

install:
  # Downloads and compiles dscanner - tool for analyzing D source code
  - git clone --depth=1 --recursive https://github.com/Hackerpilot/Dscanner.git ~/Dscanner
  - if [ ${DC} = "dmd" ]; then make -C ~/Dscanner; fi

script:
  # Dscanner check
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -s --config=.dscanner.ini || true; fi
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -S --config=.dscanner.ini || true; fi

  # Main check
  - dub build
